### ISSUE TITLE
Integracja z Flatdoc

### ISSUE THREAD

**Issue by groovy354** [Sealious/sealious.github.io#1]
Przeszukałem Internet w poszukiwaniu odpowiedniego narzędzia do stworzenia ładnej dokumentacji i znalazłem [Flatdoc](http://ricostacruz.com/flatdoc/).

Myślę, że powinniśmy się na niego przestawić, ponieważ:
* ładnie integruje się z GitHubem
* czyta i ładnie styluje dokumenty napisane w Markdown - to oznacza, że w repo możemy trzymać dokumentację czytelną dla Sublime'a, a na stronie - tę samą treść, ale w wizualnie satysfakcjonującej szacie graficznej (przykład - [ta strona](http://ricostacruz.com/flatdoc/) jest po prostu przetworzonym [ty plikiem .md](https://github.com/rstacruz/flatdoc/blob/gh-pages/Readme.md)
* pozwala na utworzenie podstron z dokumentacjami dla różnych wersji programu

ZADANIA:
* [x] dołączyć pliki Flatdoc do repo strony
* [x] wczytać i wyświetlić plik `README.md` z repo sealious/Sealious
* [x] utworzyć osobną podstronę do dokumentacji. Ta podstrona ma również być generowana przez flatdoc-a, ale ma czytać plik `reference.md` z repo sealious/Sealious

**Comment by debian-sh** [comment]
https://github.com/Sealious/sealious.github.io/commit/14a7de4492fbaf2db615cb8fd904599784f367c4

Pierwsza integracja z flatdoc-iem, niedopracowane style. Plik reference.md jeszcze nie istnieje.

**Comment by groovy354** [comment]
Super! Działa bardzo ładnie.
Myślę, że strona główna (po **solidnym** przestylowaniu) mogłaby być właśnie tym Readme.md przemielonym przez Flatdoc.
Co o tym sądzisz?

**Comment by debian-sh** [comment]
Może być ale jeszcze dużo do przeróbki, póki co czekam na reference.md, który wyświetlimy w odnośniku do Docs.

**Comment by debian-sh** [comment]
Myślę o takim kolorowaniu contentu, moja uwaga fajnie byłoby wszystkie przykłady przerzucać do nowej linii.

![image](https://cloud.githubusercontent.com/assets/5663277/8681823/111d2374-2a6a-11e5-9f0f-17a3c5659d1e.png)

**Comment by groovy354** [comment]
Moim zdaniem kolorowanie kursywy to nie jest najlepszy pomysł - zadaniem
kursywy jest zwrócenie uwagi czytelnika w trakcie czytania, a zadaniem
"pogrubienia" jest zwrócić uwagę czytelnika w trakcie "skimmowania"
(pobieżnego przeglądania) tekstu. Dlatego w kwestii kolorowego
podświetlania pogrubienia jestem na tak, a kursywy - na nie :)

**Comment by debian-sh** [comment]
Ok.

**Comment by debian-sh** [comment]
Integracja zakończona, kwestie UIowe na oddzielne issues
