### ISSUE TITLE
Problem with rendering docs after change version

### ISSUE THREAD

**Issue by debian-sh** [Sealious/sealious.github.io#22]

**Comment by groovy354** [comment]
Yes, table of contents seems to want to sneak into every DOM element :D 
@debian-sh, can you take care of this?

**Comment by debian-sh** [comment]
Maybe yes, I will try probably problem generates marky.

**Comment by debian-sh** [comment]
I don't know how to deal with marked. :<

**Comment by debian-sh** [comment]
I have some idea with toc, I will try to repair tomorrow.
