### ISSUE TITLE
Ugly homepage - new css style

### ISSUE THREAD

**Issue by debian-sh** [Sealious/sealious.github.io#6]
I propose it would be better if we will leave flatdoc fetcher in homepage. This introduces an unnecessary mess in styling and provides big content which match more to documentation / it looks like a documentation. In my opinion we don't need copy of readme, I would rather some phrases about current features instead of readme. It is more favor. What do you think?

**Comment by theadimar21** [comment]
It's ugly indeed. My thoughts:

One big image of our seal is what the user sees first - just like it is at
the moment. Right now "Sealious" "$ npm install sealious" and the three
buttons are in the middle - it looks kind of meh. Maybe moving them closer
to the bottom of the photo and placing a navbar on the top would be better.
The seal would become more visible, so maybe we should think about
shrinking the photo?
Or maybe we should do something like sails: http://sailsjs.org/ the octopus
is on the right, the logo, motto and the button is on the left.


Navbar:
Left: Button "Sealious" (or maybe an image with our logo?), on the right
three buttons "docs", "download", "view on github". Or maybe some other
options, like here: https://angularjs.org/ ?
Navbar should be fixed - when scrolling down, it should stay on the top.


When user scrolls down, he should see basic information about our
framework. Like what it is, what's the goal of the project etc. I think
placing fragments of code requires a loooot of good page styling. Right now
it's like texttexttexttexttext - blocks of text that are difficult to read.

2015-08-27 1:46 GMT+02:00 Arkadiusz Wieczorek <notifications@github.com>:

**Comment by debian-sh** [comment]
In the case of said sails, they don't have big content on (start / first look) in addition beautiful and responsive page. Ok we can leave our content. I think it's not good idea using flatdoc for fetching in homepage it excess of form. Makes it difficult to work with css styles.

**Comment by theadimar21** [comment]
I would leave only the most important parts. It needs to be well thought,
so maybe we should meet and discuss this matter?

2015-08-27 9:37 GMT+02:00 Arkadiusz Wieczorek <notifications@github.com>:

**Comment by debian-sh** [comment]
Good point

**Comment by groovy354** [comment]
I think it's a good project for Praktyki Badawcze :)

**Comment by debian-sh** [comment]
This page need new breeze. Several days should be sufficient.

**Comment by groovy354** [comment]
I've jotted it down as one of the things to take care of in September, then

**Comment by theadimar21** [comment]
Well, the layout of our page could be a project for Praktyki Badawcze, but
the content itself should be discussed within the veteran members ;)
Because we know (more or less) what Sealious is all about. The newcomers
may not be so fluent with Sealious ideas.

2015-08-28 8:03 GMT+02:00 Kuba Orlik <notifications@github.com>:

**Comment by debian-sh** [comment]
Yes, this issue is aimed at the veteran members. ;)

**Comment by debian-sh** [comment]
I'm working now on homepage, I will let you know.

**Comment by debian-sh** [comment]
@groovy354 @theadimar21 Please check current state.

**Comment by groovy354** [comment]
Looking good!

**Comment by theadimar21** [comment]
Better. But on my laptop I see this:

This font is like to thin? Dunno...

2015-08-28 13:21 GMT+02:00 Kuba Orlik <notifications@github.com>:

**Comment by groovy354** [comment]
There's no image visible  - I think you have to use the Github interface in order to embed images

**Comment by debian-sh** [comment]
Do we have embed images?

**Comment by debian-sh** [comment]
Inserting images will cause a mess.

**Comment by debian-sh** [comment]
I prefer to disable flatdoc on homepage and put it only for documentation.
